### ISSUE TITLE
Daylight saving time requirements & interpretation

### ISSUE THREAD

**Issue by DavidHollman** [open229/ruleset-model-description-schema#351]
Questions about what information for daylight savings is needed in the schema and how it is to be interpreted.

## Daylight saving time information
 
There is the `Calendar.has_daylight_saving_time` property, which is the only explicit reference to DST I can find in `docs229\ASHRAE229.schema.json` version "0.1.4". This is property is a boolean.

What is this property intended to be used for?

Will any tools consuming the JSON need to interpret hourly data with respect to clock time?  If so, this property by itself does not seem sufficient. The tool would need to know precisely when DST starts & ends. 

(ASHRAE Weather Data Viewer, for example, has this information. There is a spreadsheet with general time zone information including DST start/end rules.)

I could imagine actual clock time might be needed for reporting. For example, maybe it would be easier for users to understand reports if any time-related values are presented in the local time of the project. (I am not familiar with the schema for RCT outputs to know if this sort of thing is intended meaningful.)

## Schedule values
The annual hourly schedules are just lists of values, they do not explicitly state the date & time. e.g., `Schedule.hourly_values`.

Does this mean that schedule values have to be in local time without DST applied?  

BEM tools probably let their users specify schedules in terms of clock time, e.g., "100% occupancy begins at 8am". 

This implies that the BEM tool writing out the schedules would have to shift for DST when interpreting its own schedule data and creating the RMD JSON. Is this a correct understanding?

**Comment by JasonGlazer** [comment]
@DavidHollman isn't the rules for DST always local and appropriate for the specific climate data referenced? It seems this is more about oddities related to daylight savings like Arizona and Hawaii and certain native American reservations. 

I have always assumed that the 8784 (normally 8760) was just each successive hour in standard time. Maybe a note needs to be added for that.

**Comment by JasonGlazer** [comment]
Addressed in 0.1.6

**Comment by DavidHollman** [comment]
I saw the note added in 0.1.6:
>  The list of values is in standard time and should be adjusted when Calendar.has_daylight_saving_time is set to True based on local rules governing the start and end dates of daylighting savings time.

I agree its good for all time values in the JSON to be in standard local time.  Thus the BEM tool will be responsible for shifting appropriately into standard time when the JSON is written. 

As for the `Calendar.has_daylight_saving_time` property, I'm still not sure if this is useful information. If none of the tools consuming the JSON care about DST, then can we remove it?  But if they do need to output information with DST applied, this is not enough information to do that.

From what I remember there is huge variation when DST starts/ends worldwide (and within some countries like the USA).

**Comment by JasonGlazer** [comment]
Addressed in 0.1.7
